services:
  technical-documentation:
    build: 
      context: .
      dockerfile: dockerfile
    image: technical-documentation:latest    
    container_name: technical-documentation
    environment:
      - DB_PASSWORD="password"
    ports:
      - "3000:3000"
    networks:
      - technical-documentation-network
    depends_on:
    - db

  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./up.sql:/docker-entrypoint-initdb.d/up.sql
    command: --init-file=/docker-entrypoint-initdb.d/up.sql

networks:
  technical-documentation-network:
    name: technical-documentation-network

volumes:  
  db_data:
